// Runs after `next build`. Walks the exported site, writes out/sw.js with a
// precache list of everything in it, and drops the .nojekyll marker.
//
// The list has to be generated rather than hand-written: Next hashes asset
// filenames, so they change on every build that changes the code.

import { createHash } from "node:crypto";
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, posix, relative, sep } from "node:path";

const outDir = join(process.cwd(), "out");
const basePath = process.env.BASE_PATH ?? "/polihole";

const PRECACHE_EXTENSIONS = new Set([
  ".html",
  ".js",
  ".css",
  ".json",
  ".webmanifest",
  ".woff2",
  ".png",
  ".svg",
  ".ico",
  ".txt",
]);

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = await Promise.all(
    entries.map((entry) => {
      const full = join(dir, entry.name);
      return entry.isDirectory() ? walk(full) : [full];
    }),
  );
  return files.flat();
}

// Sorted so the version hash below doesn't move with `readdir` order.
const files = (await walk(outDir)).sort();

const urls = files
  .map((file) => relative(outDir, file).split(sep).join(posix.sep))
  .filter((rel) => PRECACHE_EXTENSIONS.has(rel.slice(rel.lastIndexOf("."))))
  .filter((rel) => !rel.endsWith(".txt") || rel.endsWith("index.txt"))
  .sort()
  // Directory index pages are requested as `/some/dir/`, not as
  // `.../index.html`, so cache them under the URL the browser will ask for.
  .map((rel) =>
    rel.endsWith("/index.html")
      ? `${basePath}/${rel.slice(0, -"index.html".length)}`
      : rel === "index.html"
        ? `${basePath}/`
        : `${basePath}/${rel}`,
  );

// Hashes the bytes, not just their length: a file with a stable path whose
// content changes at the same size (an icon, the manifest) still has to
// produce a different cache name, or the worker is byte-identical and
// installed users never see the deploy.
const digest = createHash("sha256");
for (const file of files) {
  digest.update(relative(outDir, file).split(sep).join(posix.sep));
  digest.update(await readFile(file));
}
const version = digest.digest("hex").slice(0, 12);

const sw = `// Generated by scripts/generate-sw.mjs — do not edit.
const CACHE = "polihole-${version}";
const PRECACHE = ${JSON.stringify(urls, null, 2)};
const START_URL = ${JSON.stringify(`${basePath}/`)};

// Like cache.addAll, but bypassing the HTTP cache: Pages serves pages with
// max-age=600, so a plain addAll can file a stale page under the new cache
// name for ten minutes after a deploy. Any failure rejects, which aborts the
// install and leaves the old worker in charge — a half-precached cache is
// worse than a late update.
async function precache(cache) {
  await Promise.all(
    PRECACHE.map(async (url) => {
      const response = await fetch(url, { cache: "reload" });
      if (!response.ok) throw new Error("precache failed: " + url);
      await cache.put(url, response);
    }),
  );
}

// Deliberately no skipWaiting() here. A worker that took over mid-session
// would leave the open page rendering old HTML against a new cache, and would
// pull the deck out from under a conversation. It installs, then waits.
self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then(precache));
});

// The page accepting the update on the reader's behalf. Activating replaces
// the old worker and claims the page, which is what triggers the reload on
// the other side — see lib/use-app-update.ts.
self.addEventListener("message", (event) => {
  if (event.data === "polihole:skip-waiting") self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))),
      )
      .then(() => self.clients.claim()),
  );
});

// Everything here is a build artefact with a hashed name or a page that only
// changes on deploy, so cache first and refresh in the background.
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const cached = await cache.match(request, { ignoreSearch: true });
      const network = fetch(request)
        .then((response) => {
          if (response.ok && response.type === "basic") {
            cache.put(request, response.clone());
          }
          return response;
        })
        .catch(() => null);

      if (cached) {
        event.waitUntil(network);
        return cached;
      }

      const response = await network;
      if (response) return response;

      // Offline and unseen: a navigation can still fall back to the home screen.
      if (request.mode === "navigate") {
        const fallback = await cache.match(START_URL);
        if (fallback) return fallback;
      }
      return new Response("Offline", { status: 503, statusText: "Offline" });
    }),
  );
});
`;

await writeFile(join(outDir, "sw.js"), sw);
await writeFile(join(outDir, ".nojekyll"), "");

console.log(`sw.js: ${urls.length} precached URLs (cache polihole-${version})`);
